/**
* @File Name:   NF_AccountTriggerHandler_Sample.cls
* @Description: Handles trigger for account creation
* @Author:      Thomas Winter
* @Group:       Apex
* @Modification Log :
*-------------------------------------------------------------------------------------
* Ver       Date        Author      Modification
* 1.0       2018-03-25  Thomas Winter    Created the file/class
*/
public with sharing class NF_AccountTriggerHandler_Sample extends NF_AbstractTriggerHandler {
	public override void beforeUpdate(){

	}

	public override void afterUpdate(){

	}

	public override void beforeInsert(){

	}

	public override void afterInsert(){

	}

	public override void afterDelete(){

	}

	public override void andFinally(){

	}
}
